export const rides = [
  {
    slug: "ride-1",
    driver: "John Doe",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    car: "Opel Adam",
    date: "28.05.2023",
    time: "16:00 Uhr",
    departure: "Melsungen",
    meetingpoint: "Am Sand",
    destination: "Kassel",
    seats: 1,
    price: 4,
    currency: "€",
  },
  {
    slug: "ride-2",
    driver: "Jane Doe",
    rating: "⭐️⭐️⭐️",
    car: "Opel Astra",
    date: "30.05.2023",
    time: "12:00 Uhr",
    departure: "Malsfeld",
    meetingpoint: "Festplatz",
    destination: "Melsungen",
    seats: 3,
    price: 2,
    currency: "€",
  },
  {
    slug: "ride-3",
    driver: "Max Mustermann",
    rating: "⭐️⭐️⭐️⭐️",
    car: "VW Golf",
    date: "08.06.2023",
    time: "09:00 Uhr",
    departure: "Schwarzenberg",
    meetingpoint: "DGH",
    destination: "Körle",
    seats: 2,
    price: 2,
    currency: "€",
  },
  {
    slug: "ride-4",
    driver: "Melanie Mustermann",
    car: "VW UP",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    date: "30.06.2023",
    time: "16:00 Uhr",
    departure: "Melsungen",
    meetingpoint: "Am Sand",
    destination: "Kassel",
    seats: 3,
    price: 4,
    currency: "€",
  },
  {
    slug: "ride-5",
    driver: "Martin Mustermann",
    car: "Mercedes A-Klasse",
    rating: "⭐️⭐️⭐️",
    date: "03.07.2023",
    time: "16:30 Uhr",
    departure: "Beiseförth",
    meetingpoint: "Sportplatz",
    destination: "Bebra",
    seats: 1,
    price: 3,
    currency: "€",
  },
  {
    slug: "ride-6",
    driver: "John Doe",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    car: "Opel Adam",
    date: "28.05.2023",
    time: "16:00 Uhr",
    departure: "Melsungen",
    meetingpoint: "Am Sand",
    destination: "Kassel",
    seats: 1,
    price: 4,
    currency: "€",
  },
  {
    slug: "ride-7",
    driver: "Jane Doe",
    rating: "⭐️⭐️⭐️",
    car: "Opel Astra",
    date: "30.05.2023",
    time: "12:00 Uhr",
    departure: "Malsfeld",
    meetingpoint: "Festplatz",
    destination: "Melsungen",
    seats: 3,
    price: 2,
    currency: "€",
  },
  {
    slug: "ride-8",
    driver: "Max Mustermann",
    rating: "⭐️⭐️⭐️⭐️",
    car: "VW Golf",
    date: "08.06.2023",
    time: "09:00 Uhr",
    departure: "Schwarzenberg",
    meetingpoint: "DGH",
    destination: "Körle",
    seats: 2,
    price: 2,
    currency: "€",
  },
  {
    slug: "ride-9",
    driver: "Melanie Mustermann",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    car: "VW UP",
    date: "30.06.2023",
    time: "16:00 Uhr",
    departure: "Melsungen",
    meetingpoint: "Am Sand",
    destination: "Kassel",
    seats: 3,
    price: 4,
    currency: "€",
  },
  {
    slug: "ride-10",
    driver: "Martin Mustermann",
    rating: "⭐️⭐️⭐️",
    car: "Mercedes A-Klasse",
    date: "03.07.2023",
    time: "16:30 Uhr",
    departure: "Beiseförth",
    meetingpoint: "Sportplatz",
    destination: "Bebra",
    seats: 1,
    price: 3,
    currency: "€",
  },
];
