export const rides = [
  {
    id: "1",
    driver: "John Doe",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    date: "28.05.2023",
    time: "16:00 Uhr",
    departure: "Melsungen",
    destination: "Kassel",
    seats: 1,
    price: 4,
    currency: "€",
  },
  {
    id: "2",
    driver: "Jane Doe",
    rating: "⭐️⭐️⭐️",
    date: "30.05.2023",
    time: "12:00 Uhr",
    departure: "Malsfeld",
    destination: "Melsungen",
    seats: 3,
    price: 2,
    currency: "€",
  },
  {
    id: "3",
    driver: "Max Mustermann",
    rating: "⭐️⭐️⭐️⭐️",
    date: "08.06.2023",
    time: "09:00 Uhr",
    departure: "Schwarzenberg",
    destination: "Körle",
    seats: 2,
    price: 2,
    currency: "€",
  },
  {
    id: "4",
    driver: "Melanie Mustermann",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    date: "30.06.2023",
    time: "16:00 Uhr",
    departure: "Melsungen",
    destination: "Kassel",
    seats: 3,
    price: 4,
    currency: "€",
  },
  {
    id: "5",
    driver: "Martin Mustermann",
    rating: "⭐️⭐️⭐️",
    date: "03.07.2023",
    time: "16:30 Uhr",
    departure: "Beiseförth",
    destination: "Bebra",
    seats: 1,
    price: 3,
    currency: "€",
  },
  {
    id: "6",
    driver: "John Doe",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    date: "28.05.2023",
    time: "16:00 Uhr",
    departure: "Melsungen",
    destination: "Kassel",
    seats: 1,
    price: 4,
    currency: "€",
  },
  {
    id: "7",
    driver: "Jane Doe",
    rating: "⭐️⭐️⭐️",
    date: "30.05.2023",
    time: "12:00 Uhr",
    departure: "Malsfeld",
    destination: "Melsungen",
    seats: 3,
    price: 2,
    currency: "€",
  },
  {
    id: "8",
    driver: "Max Mustermann",
    rating: "⭐️⭐️⭐️⭐️",
    date: "08.06.2023",
    time: "09:00 Uhr",
    departure: "Schwarzenberg",
    destination: "Körle",
    seats: 2,
    price: 2,
    currency: "€",
  },
  {
    id: "9",
    driver: "Melanie Mustermann",
    rating: "⭐️⭐️⭐️⭐️⭐️",
    date: "30.06.2023",
    time: "16:00 Uhr",
    departure: "Melsungen",
    destination: "Kassel",
    seats: 3,
    price: 4,
    currency: "€",
  },
  {
    id: "10",
    driver: "Martin Mustermann",
    rating: "⭐️⭐️⭐️",
    date: "03.07.2023",
    time: "16:30 Uhr",
    departure: "Beiseförth",
    destination: "Bebra",
    seats: 1,
    price: 3,
    currency: "€",
  },
];
